baseURL = "https://ansuman-satapathy.github.io/"
languageCode = "en-us"
title = "Ansuman Satapathy"
theme = "hello-friend-ng"
copyright = "CC BY-NC 4.0"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  defaultTheme    = "dark"
  enableThemeToggle = true
  showReadTime    = true
  mainSections = ["blog"]
  homeSubtitle = "Backend Engineer | Go · DevOps · Linux"

  [params.logo]
    logoText = "ansuman"      
    logoHomeLink = "/"    
    logoCursorDisabled = false
    logoCursorColor = "#932ec9ff"
    logoCursorAnimate = "2s"   

[[params.social]]
  name = "github"
  url  = "https://github.com/ansuman-satapathy"

[[params.social]]
  name = "linkedin"
  url  = "https://linkedin.com/in/ansuman-satapathy"

[[params.social]]
  name = "email"
  url  = "mailto:satapathyansuman12@gmail.com"

# --- MENU ---
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 1

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"
    weight     = 2

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true